# Generated by Django 4.0.3 on 2022-04-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_category_gameinfo_alter_gameinfo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
