# Generated by Django 4.0.3 on 2022-04-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_gameinfo_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameInfo',
            new_name='Header',
        ),
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name_plural': 'Header'},
        ),
    ]
