# Generated by Django 4.0.3 on 2022-04-04 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='GameInfo',
        ),
        migrations.AlterModelOptions(
            name='gameinfo',
            options={'verbose_name_plural': 'GameInfo'},
        ),
    ]
